### ISSUE TITLE
[Bug] Protected properties are included in args table

### ISSUE THREAD

**Issue by Yogu** [storybookjs/webpack-angular-types-plugin#21]
The args table currently includes `protected` properties of components without indicating that they are protected.

I guess in most cases, protected properties do not need to be shown at all. In an API documentation, they are only relevant for classes that are intended to be subclassed. In other cases, protected members usually are an artifact of how a component is implemented instead of part of the API.

The angular framework itself [excludes protected members from the public API](https://github.com/angular/angular/blob/main/docs/PUBLIC_API.md#supported-public-api-surface-of-angular) except for classes that are explicitly marked as non-final in the documentation.

**Comment by Etienne-Buschong** [comment]
Yes, the plan was to exclude protected and private properties and i simply overlooked the protected properties.
Since the target audience of the generated types are developers consuming public components, and not extending them, i think it is fine to always exclude protected properties.
