### ISSUE TITLE
[Bug] Properties / inputs without default value show `""` as default value

### ISSUE THREAD

**Issue by Yogu** [storybookjs/webpack-angular-types-plugin#23]
If a property has no default value, the "Default" column shows `""`. Instead, it should somehow indicate that there is no default value, e.g. leave the cell blank.

**Comment by Etienne-Buschong** [comment]
I just checked it again. The ArgsTable requires that a string is entered, so this is nothing that we can change on our side.
Would it be an okay-ish solution to explicitly write something like "No default value", or would this be too verbose?
